const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'../dist/shiro-help.js'),'utf8');
const block=source.slice(source.indexOf('const menus='),source.indexOf('function route()'));
const ctx={window:{}};vm.createContext(ctx);vm.runInContext(block,ctx);
for(const [question,link] of [['직업 비교는 어떻게 해?','explore'],['나 알아보기','quiz'],['서초고 소식','news'],['미래 변화','future'],['공부 준비','plan'],['저장 삭제','quiz']]){assert(vm.runInContext('answer('+JSON.stringify(question)+').links',ctx).includes(link));}
assert(vm.runInContext('answer("<script>alert(1)</script>").text',ctx).includes('찾지 못했어'));
const functionSource=source.slice(source.indexOf('async function sendFeedback('),source.lastIndexOf('})();'));
async function testResponse(result,ok=true){const elements={'.shiro-status':{},'.shiro-send':{},'textarea':{value:'오류 화면이 궁금해요'},'.shiro-email':{value:''},'input[type=checkbox]':{checked:true}};const data={message:'오류 화면이 궁금해요',category:'사용 질문',email:'',website:''};let payload,closed=0,notice='';const form={reportValidity:()=>true,querySelector:s=>elements[s]};class FD{get(k){return data[k]}}const c={sending:false,feedback:{hidden:false},compose:{hidden:true},close:()=>closed++,notifySuccess:text=>notice=text,FormData:FD,endpoint:'https://formsubmit.co/ajax/apuda.co.kr@gmail.com',location:{origin:'https://future.apuda.app',pathname:'/'},AbortController,setTimeout,clearTimeout,fetch:async(url,opts)=>{payload=JSON.parse(opts.body);return{ok,json:async()=>result}}};vm.createContext(c);vm.runInContext(functionSource,c);await c.sendFeedback({preventDefault(){},currentTarget:form});return{elements,payload,closed,notice}}
(async()=>{let r=await testResponse({success:true,message:'Success'});assert(r.elements['.shiro-status'].textContent.includes('접수'));assert.equal(r.elements.textarea.value,'');assert.equal(r.closed,1);assert(r.notice.includes('접수'));assert(!('answers'in r.payload));assert(!('email'in r.payload));r=await testResponse({success:false,message:'This form needs Activation.'});assert(r.elements['.shiro-status'].textContent.includes('인증'));assert(r.elements.textarea.value);assert.equal(r.closed,0);r=await testResponse({success:false},false);assert(r.elements['.shiro-status'].textContent.includes('확인하지 못'));assert(r.elements.textarea.value);console.log('PASS: specific help routing, unknown questions, minimal feedback payload, activation/error drafts and service acknowledgment');})().catch(e=>{console.error(e);process.exit(1)});
